# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='1', max_length=32, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='1', max_length=32, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.UserType'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=32, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='用户名称'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='xxx',
            field=models.CharField(max_length=32, verbose_name='类型名称'),
        ),
    ]
